name: Deploy Flutter Web to GitHub Pages

defaults:
  run:
    working-directory: package/example
on:
  push:
    branches: [ master ]
    paths:
      - 'package/**'
      - '!package/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: test clone demo web app
        run: |
          git clone https://${{secrets.USER_NAME}}:${{secrets.PAT}}@github.com/zezo357/flutter_meedu_videoplayer_example.git
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web
        
      - name: Deploy demo web app
        run: |
          cd build/web
          git init
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name Abdelaziz
          git status
          git remote add origin https://${{secrets.USER_NAME}}:${{secrets.PAT}}@github.com/zezo357/flutter_meedu_videoplayer_example.git
          git add --all
          git commit -m "update"
          git push origin HEAD:main -f

